---
- name: create an erasure code profile
  ceph.automation.ceph_ec_profile:
    name: cold-stor-profile
    k: 2
    m: 2
    plugin: isa
    crush_device_class: cold-stor
    crush_failure_domain: host
    crush_root: default
    state: present

---
- name: create a Ceph Crush erasure rule
  ceph.automation.ceph_crush_rule:
    name: pula_ec
    profile: cold-stor-profile
    rule_type: erasure

- name: create a Ceph Crush replicated rule
  ceph.automation.ceph_crush_rule:
    name: pula_replikowana
    bucket_root: default
    bucket_type: host
    device_class: hdd
    rule_type: replicated
