---
- hosts: stor01

  tasks:
    # - name: bootstrap cluster
    #   ansible.builtin.import_tasks: "bootstrap.yml"
    - name: cluster config
      ansible.builtin.import_tasks: "config.yml"
    - name: crush rules
      ansible.builtin.import_tasks: "crush.yml"
    - name: pools
      ansible.builtin.import_tasks: "pool.yml"
    - name: rgw
      ansible.builtin.import_tasks: "rgw.yml"
