---
service_type: host
addr: 10.0.0.13
hostname: stor01
location:
  root: default
  rack: rack_A
labels:
  - _admin
  - mon
  - mgr
  - osd
---
service_type: host
addr: 10.0.0.14
hostname: stor02
location:
  root: default
  rack: rack_B
labels:
  - _admin
  - mon
  - mgr
  - osd
---
service_type: host
addr: 10.0.0.15
hostname: stor03
location:
  root: default
  rack: rack_C
labels:
  - mon
  - rgw
  - osd
  - mds
---
service_type: host
addr: 10.0.0.16
hostname: stor04
location:
  root: default
  rack: rack_A
labels:
  - osd
  - rgw
  - mds
---
service_type: mon
placement:
  label: "mon"
---
service_type: mgr
service_name: mgr
placement:
  label: "mgr"
---
service_type: osd
service_id: all-available-devices
service_name: osd.all-available-devices
placement:
  label: "osd"
spec:
  data_devices:
    all: true
---
service_type: rgw
service_id: objectgw
service_name: rgw.object_storage
placement:
  count: 1
  label: "rgw"
spec:
  rgw_frontend_port: 8080
---
service_type: mds
service_id: cephfs
placement:
  count: 2
  label: "mds"
